### ISSUE TITLE
Problem loading workbooks due to headerFooter behavior

### ISSUE THREAD

**Issue by cbedwards-dfw** [JanMarvin/openxlsx2#1185] opened 2024-11-19 23:47 UTC
We're looking to integrate this package into our workflow (it seems super handy!) but our standard files have `oddFooter`s that are not being handled appropriately by `amp_split()` in  `getHeaderFooterNode()` in `wb_load` , which leads to errors when we try to load any of our files. It looks like the headerFooter format in the xml file isn't matching the expected structure?

Here's an example of the headerFooter .xml that crashes the `getHeaderFooterNode()` call in wb_load:

```
<headerFooter alignWithMargins="0">
<oddFooter>&L^ &D +&C&R</oddFooter>
</headerFooter>
```

This gets read in to the `$headerFooter` of the associated wb$worksheets item as 

```
"<headerFooter alignWithMargins=\"0\"><oddFooter>&amp;L^  &amp;D  +&amp;C&amp;R</oddFooter></headerFooter>"
```
Feeding that string into `amp_split()` produces an error.

The contents of these files are not public data, but I can probably strip down a file if it would be useful to experiment with.

**Comment by JanMarvin** [comment] 2024-11-20 07:49
Thanks for the report @cbedwards-dfw and the provided XML string! The error is caused by our fragile attempt to split the header and footer xml strings into three parts (left, center and right). Unfortunately, our internal handling of headers and footers is rather clumsy. Splitting them into three parts is no exception. I'd prefer to leave the XML string intact and only edit it when necessary, but that's a task for another rainy day. And while I'm not happy with the implemented solution, it's already taken me an hour to play around with regex and look into the OOXML standard. And for a better implementation I simply have no need ...
Therefore, it will be an “it's as good as it gets” merge.

**Comment by JanMarvin** [comment] 2024-11-20 07:59
Should be fixed in `main`. Could you give this a try?

**Closed** 2024-11-20 07:58 UTC

**Comment by cbedwards-dfw** [comment] 2024-11-20 16:57
It's working perfectly! Thank you!
