### ISSUE TITLE
set_cell_style calls get_cell_style incorrectly on line 8405 of class-workbook.R, styid <- self$get_cell_style(dims = style, sheet = sheet). Should say dims=dims

### ISSUE THREAD

**Issue by sidneyporter** [JanMarvin/openxlsx2#1045] opened 2024-06-11 23:13 UTC
> Delete this text before submitting

For best results from devs, please follow this guidance:

1. Run your examples with the latest version (`remotes::install_github("JanMarvin/openxlsx2"`)
1. Utilize the [`reprex` package](https://reprex.tidyverse.org/) and create a **minimal** reproducible example
1. Utilize [`dput()`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/dput.html) for data 
1. Provide version with `packageVersion("openxlsx2")` (if you didn't follow the step above, this will be a problem)
1. Utilize `openxlsx2::temp_xlsx()` for file saving
1. If needed, take a screen shot of your Excel workbook :camera:
1. Be friendly :smile:

**Comment by sidneyporter** [comment] 2024-06-11 23:16
wb$save() fails. Get these warning messages because style got treated as dims...
Warning messages:
1: In order(as.numeric(row_attr$r)) : NAs introduced by coercion
2: In order(as.integer(cc[, "row_r"]), col2int(cc[, "c_r"])) :
  NAs introduced by coercion
3: In inner_update(wb, sheet_id, x, rows, cells_needed) :
  NAs introduced by coercion

**Comment by JanMarvin** [comment] 2024-06-12 05:47
Hi @sidneyporter ,

indeed this looks like a bug. Though I assume that you end up at this place, because of some incorrect usage - which is most likely caused by a lack of documentation.

```R
wb <- wb_workbook()$add_worksheet()$
  add_numfmt(dims = "B1", numfmt = "#,0")

numfmt <- wb$get_cell_style(dims = "B1")

# this causes the error
wb$set_cell_style(dims = "A1", style = "numfmt")
```

At the moment this is the only way I was able to reproduce the error. And this is, because `style = "numfmt"` was used instead of `style = numfmt`. The distinction is in the quotation marks. One assigns a string `"numfmt"` and the the other a string `"1"`.

If the `"numfmt"` string is passed down, the code catches the incorrect specification of the string and tries to be smart and return something for the user. Though, its unclear, what `openxlsx2` wants to do here.

https://github.com/JanMarvin/openxlsx2/blob/a84b2ff14a84fef7e86f55b01931240151f481d1/R/class-workbook.R#L8405

If I fix the code here to use dims, the result is likely not what the user requested either. It will return a style from a cell on the sheet. A few lines below we have a similar issue (copy & paste issue):

https://github.com/JanMarvin/openxlsx2/blob/a84b2ff14a84fef7e86f55b01931240151f481d1/R/class-workbook.R#L8431

**Comment by JanMarvin** [comment] 2024-06-12 05:57
I have opened a PR in #1046

**Comment by JanMarvin** [comment] 2024-06-12 06:39
Okay, the intended use for `dims = style` was to specify another cell on the worksheet. So that something like this:

 ```R
wb_set_cell_style(dims = "A1:A4", style = "B1")
```

would apply the style from cell `B1` to cells `A1:A4`.

**Comment by JanMarvin** [comment] 2024-06-12 07:06
Closed in #1046 . Thanks for the report

**Closed by JanMarvin** 2024-06-12 07:06 UTC

**Comment by sidneyporter** [comment] 2024-06-12 18:42
Hi Jan,

As a newbie to openxlsx2, the probability of an incorrect usage is definitely non-zero. Is the code below an incorrect usage? How should it be accomplished? I have about a dozen styles that look similar to this.

WB$styles_mgr$add(create_font(color=wb_color(hex="#000000"),name="Arial",sz=9),"Arial9Blk")
CountColStyle 		<- create_cell_style(horizontal="right",vertical="center",font_id=WB$styles_mgr$get_font_id("Arial9Blk"))
WB$set_cell_style(sheet=Product,dims=rowcol_to_dims(c(DataStartRow:DataEndRow),CountCol[i]),style=CountColStyle)

Thanks,

Sidney Porter

**Comment by JanMarvin** [comment] 2024-06-12 21:03
Sidney you might want to have a look at the styling chapter here: https://janmarvin.github.io/ox2-book/chapters/openxlsx2_style_manual.html

Something like this should work:

```R
library(openxlsx2)
Product <- "sheet1"

WB <- wb_workbook()$add_worksheet(Product)

Arial9Blk <- create_font(color = wb_color(hex = "#000000"), name = "Arial", sz = 9)

WB$styles_mgr$add(Arial9Blk, "Arial9Blk")

blue <- create_fill(patternType = "solid", fgColor = wb_color("blue"))

WB$styles_mgr$add(blue, "blue")

CountColStyle <- create_cell_style(
  horizontal = "right",
  vertical = "center",
  fill_id = WB$styles_mgr$get_fill_id("blue"),
  font_id = WB$styles_mgr$get_font_id("Arial9Blk")
)

WB$styles_mgr$add(CountColStyle, "CountColStyle")

WB$set_cell_style(
  sheet = Product,
  dims = "A1", # <- something  that creates a single cell
  style = WB$styles_mgr$get_xf_id("CountColStyle")
)

if (interactive()) WB$open()
```

I'll open another PR to so that setting a style for a cell range will be possible. I haven't used the `create_*()` functions in a long time. Nowadays I simply add a style to a cell or cell range with `wb_add_*()`.

**Comment by sidneyporter** [comment] 2024-06-13 04:09
I do use about a dozen styles over 60 columns plus two layers of headers across an initially undetermined number of worksheets - one sheet per product (typically 3-10 products) plus an overall. Although I had read carefully the web page you referred me to, not being familiar with spreadsheet styling and not finding any definition of xf or dxfs either in the page or easily from google - I was under the impression that my code followed the spirit of the chapter. Clearly it did not. Thank you for the responses - they have been very helpful.

**Comment by JanMarvin** [comment] 2024-06-13 06:58
Hi, I'm glad to hear that it helped! I understand your frustration with the lack of documentation, but unfortunately, completing it is no trivial task. Despite dedicating a lot of time to this package, our resources are still limited. For instance, I was answering your question yesterday evening after a full workday while gaming with a friend online. And you are using a set of functions that I haven't touched in months (which probably is why I detected a bug straight away, which needed fixing and testing ...).

Please remember, this is open source development. None of us, at least not me, are employed to develop this package. We have no affiliation with Microsoft or any other software company. We're doing this because we want to use this package ourselves and share the code in hopes that others can benefit from it as well. And we have made significant progress:
* Added many features, which involved extensive research through numerous files and thousands of pages of Office Open XML PDF documentation, as well as developing and debugging.
* Solved many issues, from simple ones like the second PR in this issue to complex ones that required preparing files and conducting extensive trial and error to recreate specific situations.
