### ISSUE TITLE
Reading single blank cell results in error

### ISSUE THREAD

**Issue by nicojx** [JanMarvin/openxlsx2#739] opened 2023-08-17 13:18 UTC
I need to read a single cell in a number of equivalent workbooks. In some of these workbooks that cell is empty, but I'd expect `wb_read` to return NA rather than fail.

This demonstrates the problem:
```R
wb <- wb_workbook()$add_worksheet()$add_data(x = "a", startCol = 2, startRow = 2, na.strings = NULL)
wb_read(wb, colNames = FALSE, rows = 1, cols = 1)
# Error in `$<-.data.frame`(`*tmp*`, "val", value = NA_character_) : 
#  replacement has 1 row, data has 0
```

Tested with `openxlsx2` version 0.8.

**Comment by JanMarvin** [comment] 2023-08-17 13:36
Thanks @nicojx , indeed this looks like a bug. In the meantime you can use `dims = "A1"`

**Comment by nicojx** [comment] 2023-08-17 13:38
Ah, that's a good shout! Thanks. Also for all your amazing work on this! :)

**Comment by JanMarvin** [comment] 2023-08-17 16:48
@nicojx in #740 I pushed a fix. The issue is, that the cell you want to return, is not part of the worksheet.

This can be seen in the cc data frame (which contains all cells of the workbook). In the openxml specifications only those cells that are filled with meaningful data have to be part of the worksheet. Most likely to save some space. Otherwise you'd have to initialize many empty cells in workbooks.

``` r
library(openxlsx2)
wb <- wb_workbook()$add_worksheet()$add_data(x = "a", startCol = 2, startRow = 2, na.strings = NULL)
wb$worksheets[[1]]$sheet_data$cc
#>    r row_r c_r c_s       c_t c_cm c_ph c_vm v f f_t f_ref f_ca f_si
#> 1 B2     2   B     inlineStr                                       
#>                  is typ
#> 1 <is><t>a</t></is>   4
```

Since `cols`  and `rows` behaves differently than `dims`, we previously reduced `cc` to an empty data frame and afterwards try to assign `NA_character_` to selected columns of the empty data frame and R complained. In release `0.8` we tried to reduce much of the previous ambiguity of arguments. Though we tried our best not to break existing code, have a look at `wb_dims()`. In general we advise users to rely on `dims`, though the `wb_to_df()` functions are a bit special in this regard.

**Closed** 2023-08-17 16:54 UTC

**Comment by JanMarvin** [comment] 2023-08-17 16:56
Thank you for the report and the kind words :heart_eyes:
